# Generated by Django 5.1.4 on 2024-12-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_rename_number_stockitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='total',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='week1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='week2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='week3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='week4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='week5',
            field=models.IntegerField(default=0),
        ),
    ]
