# Generated by Django 5.1.4 on 2024-12-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_stockitem_total_stockitem_week1_stockitem_week2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.IntegerField(),
        ),
    ]
