# Generated by Django 5.1.4 on 2025-01-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_alter_stockitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
