# Generated by Django 5.1.4 on 2025-01-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_alter_stockitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='category',
            new_name='available_quantity',
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='name',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='price',
            new_name='net_consumed',
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='quantity',
            new_name='scope_quantity',
        ),
    ]
